version: '3.1'


services:

    app:
        build: 
          context: .
          dockerfile: Dockerfile
        image: electrackapp
        container_name : app
        restart : unless-stopped
        volumes :
            -  ./:/var/www
      


    db:
      image: mariadb:10.3
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: notSecureChangeMe
      volumes: 
        - './.docker/db:/var/lib/mysql'

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8088:80
        environment:
          - PMA_ARBITRARY=1
          


    webserver:
        build:
          context: .
          dockerfile: dockerfileNginx.DOCKERFILE
        image : nginx
        container_name : webserver
        restart : unless-stopped
        ports :
            - 80:80
            - 443:443
        volumes :
            -  ./:/var/www
            - ./config/nginx/:/etc/nginx/conf.d/
        depends_on:
        - app

    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        volumes:
           - ./uptime-kuma-data:/app/data
        ports:
           - 3001:3001 
           - 445:443

        restart: always   

    mail:
      image: namshi/smtp
      environment:
        - MAIL_USER=user
        - MAIL_PASS=pass
      ports:
        - "25:25"