global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['46.226.107.16:9090']

  - job_name: 'webserver'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:9100']


  - job_name: 'webserver_2'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:9110']


  - job_name: 'db'
    scrape_interval: 5s
    static_configs:
      - targets: ['db:9104']